name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean build analyze -project "GLLara.xcodeproj" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Test
        run: |
          xcodebuild -project "GLLara.xcodeproj" -scheme "GLLara" test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Archive
        run: |
          xcodebuild archive -project "GLLara.xcodeproj" -scheme "GLLara" -archivePath GLLaraNightly.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Export
        run: |
          xcodebuild -project "GLLara.xcodeproj" -exportArchive -archivePath GLLaraNightly.xcarchive -exportPath GLLaraNightly -exportOptionsPlist .github/exportGithub.plist CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
      - name: Tar files
        run: tar -cvf GLLaraNightly.tar GLLaraNightly
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: GLLaraNightly
          path: |
            GLLaraNightly.tar

